### ISSUE TITLE
Trello card Form Name [type of law]  checklist 1.3A prepare the PDF needs updating

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine-documentation#179]
Trello card [Form Name [type of law]](https://trello.com/c/uRD0ZIOc) Checklist 1.3A Prepare the PDF 

Refers to the PDF Quality Checker - Has the checker been rolled into AL Weaver or it just that the link is broken?

- [ ]  Upload your PDF to the [PDF quality checker](https://apps-dev.suffolklitlab.org/start/assemblylinewizard/pdf_field_tester/). Do NOT download the document the PDF checker shows you at the end. You are not supposed to use that generated document.
- [ ] Does the PDF checker show that your fields are of the right type? Checkbox, text field, or signature field.
- [ ] There is a column in the PDF checker that identifies which of the labels on your PDF match up with names the code generator (the ALWeaver you will be using in the next step) will recognize. Do the values there match up with your intentions?
- [ ] On the last page of the PDF checker, make sure you can see a signature in every signature field. If you cannot, try editing the document again. Delete the old field and add in a new signature field.
- [ ] Do NOT download the document the PDF checker shows you at the end. You are not supposed to use that generated document.
- [ ] Uncheck the boxes above, make any necessary changes, and go through them again using the PDF checker. Repeat this until the document is ready.
