### ISSUE TITLE
Update the interview project roadmap [checklist]

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-AssemblyLine-documentation#464]
- [x] Restructure [this sentence](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/da485bcea87079faeeb13dc927a230e6ca20d80a/docs/get_started/roadmap.md?plain=1#L8) so it is easier to read (the hyphen right before the em dash makes it weird: "getting started on an interview-building project—whether it is your first or fiftieth")
- [x] Link to the [skateboard analogy source](https://blog.crisp.se/2016/01/25/henrikkniberg/making-sense-of-mvp)
- [x] Consider [this change](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1740204781)
- [x] Make it more clear that the best place to find someone with Document Assembly Line experience [for preliminary feedback](https://assemblyline.suffolklitlab.org/docs/get_started/roadmap#preliminary-feedback) is at Monday meetings or in Teams
- [x] Consider reducing the detail about [preparing for feedback](https://assemblyline.suffolklitlab.org/docs/get_started/roadmap#preliminary-feedback) (see [this comment](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1740278730) as well as #462)
- [x] Consider [this change](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1741306493)
- [x] Make [this change](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1741307124) and consider whether we can suggest solutions
- [x] Emphasize that it's a good idea to do a retrospective any time the project fails early (add this to the intro section)
- [x] Consider mentioning promotion early as party of feasibility analysis (see [this comment](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1741313747))
- [x] Change "you" to the "the project manager" in the retrospective section (see [this comment](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1741325215))
- [x] Clarify [what to do with retrospective learnings](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/459#discussion_r1741331606)

**Comment by samglover** [comment]
Link to this video: https://youtu.be/4j7rRRvsbfY
